name: Rust CI

on: [push, pull_request]

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check formatting
      run: |
        cargo fmt -- --check

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run tests
      run: |
        cargo test --all

  fix-check:
    name: Fix Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Check fixes
      run: |
        cargo fix --all --locked --allow-dirty
        git diff --exit-code || (echo "Code changes were made by cargo fix. Please run it locally and push the changes." && exit 1)
